USE [master]
GO
/****** Object:  Database [AgentPortalAudit]    Script Date: 9/8/2021 11:11:16 PM ******/
CREATE DATABASE [AgentPortalAudit]
GO
ALTER DATABASE [AgentPortalAudit] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AgentPortalAudit].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AgentPortalAudit] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET ARITHABORT OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AgentPortalAudit] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AgentPortalAudit] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AgentPortalAudit] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AgentPortalAudit] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AgentPortalAudit] SET  MULTI_USER 
GO
ALTER DATABASE [AgentPortalAudit] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AgentPortalAudit] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AgentPortalAudit] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AgentPortalAudit] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AgentPortalAudit] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AgentPortalAudit] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [AgentPortalAudit] SET QUERY_STORE = OFF
GO
USE [AgentPortalAudit]
GO
/****** Object:  Table [dbo].[Audits]    Script Date: 9/8/2021 11:11:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Audits](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedAt] [bigint] NOT NULL,
	[UpdatedAt] [bigint] NOT NULL,
	[AuditDateTimeUtc] [bigint] NOT NULL,
	[AuditType] [nvarchar](30) NOT NULL,
	[AuditUser] [nvarchar](50) NOT NULL,
	[TableName] [nvarchar](max) NOT NULL,
	[KeyValues] [nvarchar](max) NOT NULL,
	[OldValues] [nvarchar](max) NOT NULL,
	[NewValues] [nvarchar](max) NOT NULL,
	[ChangedColumns] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Audits] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Audits] ADD  DEFAULT (CONVERT([bit],(1))) FOR [IsActive]
GO
USE [master]
GO
ALTER DATABASE [AgentPortalAudit] SET  READ_WRITE 
GO
